# Generated by Django 3.0.7 on 2020-06-09 18:32

import main.mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("django_celery_beat", "0012_periodictask_expire_seconds"),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="BeautifulPeriodicTask",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("django_celery_beat.periodictask",),
        ),
        migrations.CreateModel(
            name="CheckedHash",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_ts", models.DateTimeField(auto_now_add=True)),
                ("hacked_ts", models.DateTimeField(blank=True, null=True)),
                ("is_finished", models.BooleanField(default=False)),
                ("is_active", models.BooleanField()),
                (
                    "_encrypted_hash",
                    models.TextField(blank=True, default=None, null=True),
                ),
                (
                    "_encrypted_password",
                    models.TextField(blank=True, default=None, null=True),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="main.Account"
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="main.BeautifulPeriodicTask",
                    ),
                ),
            ],
            bases=(
                models.Model,
                main.mixins.EncryptedHashMixin,
                main.mixins.EncryptedPasswordMixin,
            ),
        ),
    ]
