# Generated by Django 3.0.7 on 2020-06-16 10:08

import main.mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("django_celery_beat", "0012_periodictask_expire_seconds"),
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BruteConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("min_length", models.IntegerField(verbose_name="Минимальная длина")),
                ("max_length", models.IntegerField(verbose_name="Максимальная длина")),
                ("digits", models.BooleanField(verbose_name="Цифры (0-9)")),
                ("upper_case_en", models.BooleanField(verbose_name="Английский (A-Z)")),
                ("lower_case_en", models.BooleanField(verbose_name="Английский (a-z)")),
                ("upper_case_ru", models.BooleanField(verbose_name="Русский (А-Я)")),
                ("lower_case_ru", models.BooleanField(verbose_name="Русский (а-я)")),
                ("symbols", models.BooleanField(verbose_name="Символы")),
                (
                    "custom_alphabet",
                    models.TextField(
                        blank=True, null=True, verbose_name="Свой алфавит"
                    ),
                ),
            ],
            bases=(models.Model, main.mixins.AlphabetMixin),
        ),
        migrations.CreateModel(
            name="Dictionary",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("path", models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name="BeautifulPeriodicTask",
        ),
        migrations.CreateModel(
            name="BruteforcePeriodicTask",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("django_celery_beat.periodictask",),
        ),
        migrations.CreateModel(
            name="DictionaryPeriodicTask",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("django_celery_beat.periodictask",),
        ),
        migrations.AlterField(
            model_name="checkedhash",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="django_celery_beat.PeriodicTask",
            ),
        ),
    ]
