# Generated by Django 3.0.7 on 2020-06-18 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("django_celery_beat", "0012_periodictask_expire_seconds"),
        ("main", "0002_auto_20200616_1008"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnotherPeriodicTask",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("django_celery_beat.periodictask",),
        ),
        migrations.AlterModelOptions(
            name="checkedhash",
            options={
                "verbose_name": "Checked hash",
                "verbose_name_plural": "Checked hashes",
            },
        ),
        migrations.AlterModelOptions(
            name="dictionary",
            options={
                "verbose_name": "Dictionary",
                "verbose_name_plural": "Dictionaries",
            },
        ),
    ]
