# Generated by Django 3.0.7 on 2020-07-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_auto_20200618_1016"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bruteforceperiodictask",
            options={
                "verbose_name": "Bruteforce periodic task",
                "verbose_name_plural": ">Bruteforce periodic tasks",
            },
        ),
        migrations.AlterModelOptions(
            name="dictionaryperiodictask",
            options={
                "verbose_name": "Dictionary periodic task",
                "verbose_name_plural": ">Dictionary periodic tasks",
            },
        ),
        migrations.AlterModelOptions(
            name="otherperiodictask",
            options={
                "verbose_name": "Other periodic task",
                "verbose_name_plural": ">Other periodic tasks",
            },
        ),
        migrations.AlterField(
            model_name="bruteconfig",
            name="digits",
            field=models.BooleanField(verbose_name="Цифры (0-9)              x10"),
        ),
        migrations.AlterField(
            model_name="bruteconfig",
            name="lower_case_en",
            field=models.BooleanField(verbose_name="Английский (a-z)  x26"),
        ),
        migrations.AlterField(
            model_name="bruteconfig",
            name="lower_case_ru",
            field=models.BooleanField(verbose_name="Русский (а-я)     x33"),
        ),
        migrations.AlterField(
            model_name="bruteconfig",
            name="symbols",
            field=models.BooleanField(verbose_name="Символы                 x33"),
        ),
        migrations.AlterField(
            model_name="bruteconfig",
            name="upper_case_en",
            field=models.BooleanField(verbose_name="Английский (A-Z)  x26"),
        ),
        migrations.AlterField(
            model_name="bruteconfig",
            name="upper_case_ru",
            field=models.BooleanField(verbose_name="Русский (А-Я)     x33"),
        ),
        migrations.AlterField(
            model_name="checkedhash",
            name="account",
            field=models.CharField(max_length=256),
        ),
        migrations.DeleteModel(
            name="Account",
        ),
    ]
