# Generated by Django 3.0.8 on 2020-07-03 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_auto_20200702_1354"),
    ]

    operations = [
        migrations.RenameField(
            model_name="checkedhash",
            old_name="account",
            new_name="login",
        ),
        migrations.RemoveField(
            model_name="checkedhash",
            name="task",
        ),
        migrations.AddField(
            model_name="checkedhash",
            name="brute_config",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="main.BruteConfig",
            ),
        ),
        migrations.AddField(
            model_name="checkedhash",
            name="db_type",
            field=models.CharField(default="", max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="checkedhash",
            name="dictionary",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="main.Dictionary",
            ),
        ),
        migrations.AddField(
            model_name="checkedhash",
            name="host",
            field=models.CharField(default="", max_length=256),
            preserve_default=False,
        ),
    ]
