# Generated by Django 3.0.8 on 2020-07-03 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_auto_20200703_1602"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CheckedHash",
            new_name="Hash",
        ),
    ]
