# Generated by Django 3.0.8 on 2020-07-06 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_auto_20200703_1604"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hash",
            name="is_active",
        ),
        migrations.AddField(
            model_name="hash",
            name="account_status",
            field=models.CharField(default="", max_length=48),
        ),
        migrations.AddField(
            model_name="hash",
            name="is_changed",
            field=models.BooleanField(default=False),
        ),
    ]
