# Generated by Django 3.0.8 on 2020-07-10 16:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_auto_20200708_1507"),
    ]

    operations = [
        migrations.RemoveField(model_name="hash", name="ip"),
        migrations.AddField(
            model_name="hash",
            name="ip",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.GenericIPAddressField(),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
