# Generated by Django 3.0.8 on 2020-07-21 09:51

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_auto_20200717_1142"),
    ]

    operations = [
        migrations.CreateModel(
            name="Database",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("host", models.CharField(max_length=256)),
                (
                    "ip",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.GenericIPAddressField(),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                ("port", models.IntegerField(blank=True, default=None, null=True)),
                ("db_type", models.CharField(max_length=32)),
            ],
            managers=[
                ("object", django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name="hash",
            name="db_type",
        ),
        migrations.RemoveField(
            model_name="hash",
            name="host",
        ),
        migrations.RemoveField(
            model_name="hash",
            name="ip",
        ),
        migrations.AddField(
            model_name="hash",
            name="database",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                to="main.Database",
            ),
            preserve_default=False,
        ),
    ]
