# Generated by Django 3.0.8 on 2020-07-21 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("django_celery_beat", "0012_periodictask_expire_seconds"),
        ("main", "0012_auto_20200721_0951"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OtherPeriodicTask",
        ),
        migrations.AlterModelManagers(
            name="database",
            managers=[],
        ),
    ]
