# Generated by Django 3.0.8 on 2020-07-23 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_auto_20200721_1058"),
    ]

    operations = [
        migrations.AddField(
            model_name="hash",
            name="cracking_started_ts",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
