# Generated by Django 3.0.8 on 2020-08-04 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_hash_cracking_started_ts"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bruteforceperiodictask",
            options={
                "verbose_name": "Bruteforce periodic task",
                "verbose_name_plural": "\u2063\u2063\u2063\u2063\u2063\u2063Periodic tasks: Bruteforce",
            },
        ),
        migrations.AlterModelOptions(
            name="dictionaryperiodictask",
            options={
                "verbose_name": "Dictionary periodic task",
                "verbose_name_plural": "\u2063\u2063\u2063\u2063Periodic tasks: \u2063\u2063\u2063Dictionary",
            },
        ),
    ]
