# Generated by Django 3.0.8 on 2020-08-06 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0015_auto_20200804_2005"),
    ]

    operations = [
        migrations.AddField(
            model_name="dictionary",
            name="file_size",
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dictionary",
            name="word_count",
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
