# Generated by Django 3.1 on 2020-08-13 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0016_auto_20200806_1125"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dictionary",
            name="file_size",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="dictionary",
            name="word_count",
            field=models.BigIntegerField(default=0),
        ),
    ]
