# Generated by Django 3.1 on 2020-08-20 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0017_auto_20200813_1313"),
    ]

    operations = [
        migrations.AddField(
            model_name="database",
            name="is_disabled",
            field=models.BooleanField(default=False),
        ),
    ]
