# Generated by Django 3.1 on 2020-08-20 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0018_database_is_disabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="database",
            name="is_connected",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="database",
            name="last_check_ts",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
