# Generated by Django 3.1 on 2020-08-24 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0019_auto_20200820_1405"),
    ]

    operations = [
        migrations.RenameField(
            model_name="database",
            old_name="last_check_ts",
            new_name="last_connect_ts",
        ),
        migrations.AddField(
            model_name="database",
            name="is_pulled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="database",
            name="last_pull_ts",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
