# Generated by Django 3.1 on 2020-08-29 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("django_celery_beat", "0012_periodictask_expire_seconds"),
        ("main", "0020_auto_20200824_2206"),
    ]

    operations = [
        migrations.CreateModel(
            name="OtherPeriodicTask",
            fields=[],
            options={
                "verbose_name": "Other periodic task",
                "verbose_name_plural": "Periodic tasks: Other",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("django_celery_beat.periodictask",),
        ),
    ]
